### ISSUE TITLE
[Enigma] Константы

### ISSUE THREAD

**Issue by pavel-b-novikov** [rogolev/nsudotnet#1]
private readonly static string

Это что-то на уровне Высоцкого. Может даже выше.

**Comment by rogolev** [comment]
Исправлено.

**Comment by pavel-b-novikov** [comment]
По константам еще один вопрос: а какие типы могут быть объявлены константами и почему?

**Comment by rogolev** [comment]
Value-types, потому что иначе константной объявляется ссылка на объект, а не сам объект

**Comment by rogolev** [comment]
Константными могут быть объявлены только встроенные типы C#, исключая тип object, т.к. значение константы должно быть известно во время компиляции.

**Comment by pavel-b-novikov** [comment]
Гыг. А ответ про value types по-прежнему сохранился в e-mail-е.
Засчитано.

**Comment by rogolev** [comment]
Ну, как говорится, слово - не воробей
