### ISSUE TITLE
TaskScheduler

### ISSUE THREAD

**Issue by sfactor** [rogolev/nsudotnet#4]
- использование системных таймеров для delayed и periodic jobs
- использование thread pool для cron jobs

**Comment by sfactor** [comment]
Очень, очень много вопросов. Прошу пока пока ответить на них комментариями к этому issue, а потом, возможно, и до правки кода доберемся.
1. Чего хотелось достичь вызовом `_mutex.GetAccessControl()` в `JobsManager.ManageJobs()` и `DelayedJobsManager.DoJobsManagement()`?
2. Почему используется нативный thread pool? (особенно имея в виду, что `System.Timers.Timer` сам по себе позволяет запустить хэндлер в отдельном треде?)
3. (тут должен был быть вопрос о том, зачем у таймеров дергается `Dispose()` и почему все классы реализуют `IDisposable`, но начнем с более фундаментального вопроса) Что делает метод `Dispose()`?

И пара общих комментариев:
1. Удаление таймеров из HashSet-а в `DelayedJobManager` — чудовищный хак. Только ради того, чтобы избежать этого, стоило переработать вообще всю архитектуру (зачем нам складывать в контейнер таймеры, если они нам нужны только один раз?)
2. Вообще говоря, хранение таймеров в контейнере при текущей реализации бессмысленно: их имеет смысл хранить (и то только для periodic jobs и cron jobs) только в случае, если интерфейс библиотеки подразумевает остановку задач — тогда нам действительно надо найти соответствующий задаче таймер и остановить его. А при текущей реализации мы можем просто создавать таймеры и спокойно отпускать их в «свободное плаванье» в managed heap – все равно нам больше не понадобятся ссылки на них.

Я отдаю ведомость в понедельник утром, поэтому у тебя еще есть время побороться за пятерку. Пока реализация содержит следы фундаментального непонимания некоторых моментов, полный балл ставить не за что.

**Comment by rogolev** [comment]
1. _mutex.GetAccessControl() оказался в том месте по случайности - там должен быть _mutex.WaitOne().
2. System.Threading.Timer и правда позволяет запустить задачу на исполнение в отдельном потоке, но в случае с отложенными заданиями нужно тогда передать параметром period TimeSpan от нуля или отрицательного значения, причем я не понял, что именно происходит в этом случае. 
3. У таймеров делается Dispose() потому что я следовал принципу: задиспожено должно быть все, что реализует IDisposable.

**Comment by rogolev** [comment]
А в DelayedJobsManager _mutex.GetAccessControl() или _mutex.WaitOne() вообще оказаться не должно было

**Comment by rogolev** [comment]
Да, еще момент: собственно, хранятся-то таймеры лишь только для того, чтобы их можно было задиспозить.

**Comment by rogolev** [comment]
Вообще, я подозревал, что использовать Dispose() для Timer необязательно, но не нашел таких слов на msdn.

**Comment by rogolev** [comment]
Оу, я понял, почему можно не диспозить таймер: ведь при отсутствии ссылки на него он тем не менее продолжает функционировать, выходит, она где-то хранится, значит можно надеяться на то, что он (скорее всего где-то к концу приложения или при отсутствии активности) будет корректно задиспожен.

**Comment by rogolev** [comment]
И ответ на последний ваш вопрос про Dispose: Dispose выполняет некоторые действия, связанные с освобождением ресурсов.

**Comment by sfactor** [comment]
Я тут полез в сорцы .NET-а и узнал много интересного про таймеры:) Завтра дообсудим.

> Да, еще момент: собственно, хранятся-то таймеры лишь только для того, чтобы их можно было задиспозить.

Так и не получил ответа: а зачем их диспозить?

**Comment by rogolev** [comment]
Ну, просто услышал я однажды такое: все, что реализует интерфейс IDisposable, должно быть задиспожено. Вот и задиспозил как сумел.

**Comment by sfactor** [comment]
Ок, я тут на свежую голову обдумал задачу и использование таймеров в целом. Некоторые мои предыдущие комментарии были не по делу, приношу извинения.

Вообще пришло запоздалое понимание, что таймеры для этой задачи — ужасный инструмент, но все другие (правильные) реализации этой задачи еще сложнее:) Пусть пока будут таймеры.
1. Таймеры действительно нужно складывать в контейнер (или любым другим способом сохранять ссылки на них). Если на таймер нет внешних ссылок, то даже если он работает, за ним все равно может прийти GC (так нас учит MSDN).
2. Таймеры действительно нужно диспозить после использования, иначе они будут бесцельно занимать лишний тред (тот, в котором идет отсчет времени). Без регулярного диспоза мы при долгом использовании можем нагенерить огромное количество балластных тредов и застопорить всю систему. 
3. Создавать лишний тред через thread pool при срабатывании таймера — самая грубая ошибка текущей реализации. По факту мы генерим в два раза больше тредов, чем нужно.
4. Вызовы `Dispose()` в целом все по делу (учитывая, что таймеры действительно нужно явно диспозить). Однако если мы уж начали реализовывать dispose pattern, то почему проигнорирован финализатор? Вполне возможна ситуация, когда пользователь забыл дернуть `TaskManager.Dispose()`, и тогда после сборки `TaskManager`-а сборщиком мусора всё останется в неконсистентном состоянии: `TaskManager`-а нет, таймеры живы и генерят эвенты, рабочие треды текущих хэндлеров тоже живы, всюду разброд и шатание.

Про dispose pattern: https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx

**Comment by rogolev** [comment]
Здравствуйте, прошу прощения за задержку, внес исправления по пунктам 3 и 4.

**Comment by sfactor** [comment]
Снова вопросы:
1. Как связан `Dispose()` и сборка мусора? 
2. Что делает `GC.SuppressFinalize()`?

**Comment by rogolev** [comment]
1. Dispose() и сборка мусора выполняют одну задачу - освобождение неиспользуемых ресурсов. В то время как сборщик мусора освобождает память, в задачу Dispose() входит освобождение неуправляемых ресурсов.
2. GC.SupperssFinalize(obj) сообщает сборщику мусора, что объект, obj не нуждается в финализации, т.е. его финализатор можно не вызывать.

**Comment by rogolev** [comment]
И еще, по четвертому пункту вашего issue, где вы говорите про Dispose pattern. Финализатор был проигнорирован, т.к. классы в задаче TaskManager, реализующие IDisposale, не содержат unmanaged ресурсов.

**Comment by sfactor** [comment]
> Финализатор был проигнорирован, т.к. классы в задаче TaskManager, реализующие IDisposale, не содержат unmanaged ресурсов.

Да, эта мысль верна и постоянно повторяется во всех статьях про `IDisposable` на MSDN, однако к этой задаче она неприменима.

`Dispose()` **не вызывается сборщиком мусора** ни в каком виде. Никогда. 
Сборщик мусора вызывает только финализаторы.

Что происходит, если для произвольного disposable-объекта пользователь забывает явно вызвать `Dispose()` (или обернуть использование объекта в `using`)? Вообще говоря, ничего страшного: при отсутствии использования unmanaged-ресурсов, всё, что может внутри объекта требовать освобождения — это точно такие же disposable-объекты (ну или тупо память, но ей займется GC). В конечном итоге все пользовательские disposable-объекты сводятся к системным disposable-объектам, а все они повторяют логику освобождения ресурсов и в `Dispose()`, и в финализаторе. Короче говоря, когда до пользовательского disposable-объекта доберется GC, то логика освобождения ресурсов будет полностью выполнена. 

Именно поэтому забывать позвать `Dispose()` для disposable-классов — не очень страшная ошибка, т.к. логика деинициализации все равно выполнится (хоть и в неопределенный момент времени).

Но в случае твоей реализации мы скованы использованием таймеров, будь они неладны. Даже несмотря на то, что это managed-ресурс с честной логикой деинициализации и в `Dispose()` и финализаторе, они приводят к огромным проблемам. Еще раз описываю ситуацию:
- Пользователь прекратил пользоваться твоим `TaskManager`-ом (читай —потерял все ссылки на него), но забыл вызвать ему `Dispose()`.
- GC собрал `TaskManager` и, в силу своей природы, не позвал ему `Dispose()`
- `TaskManager`-а больше нет, А ТАЙМЕРЫ-ТО ВСЕ ЖИВЫ!! Да, на них нет ссылок, и рано или поздно они все будут собраны GC, но какое-то время они живы и генерят эвенты.

(ну и запущенные на момент сбора `TaskManager`-а треды хэндлеров тоже никто не убьет, и они продолжат свою работу, но это уже меньшее из зол)

Это архитектурная катастрофа, таких ситуаций нужно избегать. Например, потворением логики `Dispose()` в финализаторе `TaskManager`-а, чтобы мы были уверены, что когда за ним пришел GC, всё (включая таймеры и треды) действительно остановилось и умерло.

Короче, смысл всей этой тирады простой: реализуй финализаторы, и будет тебе пятерка.

(и пустой метод `Dispose()` убери, пока его никто не увидел)

**Comment by rogolev** [comment]
Финализаторы добавил.

**Comment by sfactor** [comment]
Последний вопрос: что дает выставление в  `Dispose()` полей класса в null?

**Comment by rogolev** [comment]
Ну, то, что функция Dispose() была вызвана говорит о том, что объект, у которого она была вызвана, уже не нужен. Но это ничего не говорит сборщику мусора. И ссылка на него еще может где-то присутствовать, что не позволяет GC собрать его и объекты, на которые он ссылается. С тем, что ссылка на задиспоженный объект где-то осталась, сделать ничего не представляется возможным, но, по крайней мере, те объекты, на которые он ссылался, GC соберет.

**Comment by sfactor** [comment]
Идея корректная, но это излишняя перестраховка: логика освобождения ресурсов уже выполнилась в `Dispose()`, всё, чем мы рискуем — несколькими десятками неосвобожденных вовремя байт.

А вот зануление полей (и постоянная проверка их на неравенство NULL в рабочих методах класса) — потенциальный источник ошибок.

Короче, не надо так делать.

Задачу зачитываю, итоговая оценка 5.

**Comment by rogolev** [comment]
Понял. Спасибо.
